StackbyDeque: Stack_by_Deque.cpp
	g++ $^ -o StackbyDeque.out

QueuebyStack:Queue_by_Stack.cpp
	g++ Queue_by_Stack.cpp -o Queue_by_Stack.out

PQueue:PQueue.cpp
	g++ PQueue.cpp -o PQueue.out

clean: 
	rm *.out